# Generated by Django 5.2.4 on 2025-08-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0002_alter_aprendiz_options_remove_aprendiz_programa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendizcurso',
            name='fecha_inscripcion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Inscripción'),
        ),
    ]
