# Generated by Django 5.2.4 on 2025-08-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0003_alter_aprendizcurso_fecha_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprendiz',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='ciudad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='correo',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aprendiz',
            name='telefono',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='aprendizcurso',
            name='fecha_inscripcion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='estado',
            field=models.CharField(choices=[('PRO', 'Programado'), ('INI', 'Iniciado'), ('EJE', 'En Ejecución'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado'), ('SUS', 'Suspendido')], default='PRO', max_length=3, verbose_name='Estado del Curso'),
        ),
        migrations.AlterField(
            model_name='instructorcurso',
            name='fecha_asignacion',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación'),
        ),
        migrations.AlterField(
            model_name='instructorcurso',
            name='rol',
            field=models.CharField(max_length=100, verbose_name='Rol en el Curso'),
        ),
    ]
